name: Weekly Task

on:
  schedule:
    - cron: "0 8 * * MON"  # At 09:00 UTC every Monday
  workflow_dispatch:  # Allows manual triggering if you want

jobs:
  run-python-task:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  
      - name: Install requirements
        run: pip install -r requirements.txt  # omit if you don't have requirements

      - name: Install Catalan locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ca_ES.UTF-8
          sudo update-locale LANG=ca_ES.UTF-8

      - name: Set environment variables
        run: |
          echo "LANG=ca_ES.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=ca_ES.UTF-8" >> $GITHUB_ENV


      - name: Run script
        env:
          # Add your secrets here, mapping them to environment variables
          EMAIL: ${{ secrets.berta.llugany@gmail.com}}
          PASSWORD: ${{ secrets.lczz eikt rbqv ghns }}
          RECIPIENTS: ${{ secrets."berta.llugany@gmail.com, bertallugany@gencat.cat,mmulet94@gmail.com,oleguer.gabernet@gmail.com, camarelo@gencat.cat,ebertran@gencat.cat,ecasanovasm@gencat.cat,mfajardo_ext@gencat.cat,albert.font@gencat.cat,helena.linares@gencat.cat,belllodra@gencat.cat,amonreal@gencat.cat,jmmussons@gencat.cat,mariaorriols@gencat.cat,xavieralexandrepedros@gencat.cat"}}
          # LANG and LC_ALL are already set from the previous step via GITHUB_ENV
        run: python idescat_calendar.py
