name: Weekly Task

on:
  schedule:
    - cron: "0 8 * * MON"  # At 09:00 UTC every Monday
  workflow_dispatch:  # Allows manual triggering if you want

jobs:
  run-python-task:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
  
      - name: Install requirements
        run: pip install -r requirements.txt  # omit if you don't have requirements

      - name: Install Catalan locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen ca_ES.UTF-8
          sudo update-locale LANG=ca_ES.UTF-8

      - name: Set environment variables
        run: |
          echo "LANG=ca_ES.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=ca_ES.UTF-8" >> $GITHUB_ENV


      - name: Run script
        env:
          # Add your secrets here, mapping them to environment variables
          # Reference the *names* of your secrets, not their values.
          # These names must match exactly what you defined in GitHub Secrets.
          EMAIL: ${{ secrets.EMAIL_ADDRESS }}
          PASSWORD: ${{ secrets.APP_PASSWORD }}
          RECIPIENTS: ${{ secrets.RECIPIENT_LIST }}
          
          # LANG and LC_ALL are already set from the previous step via GITHUB_ENV
        run: python idescat_calendar.py
